# Generated by Django 4.1.1 on 2022-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_answer_answer_answer_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_open',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
