# Generated by Django 4.1.1 on 2022-10-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_answer_is_open_answer_answer_question_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=200),
        ),
    ]
